### ISSUE TITLE
installation is not possible in capacitor 5 version

### ISSUE THREAD

**Issue by gitmaxmatch** [TheeMachine/presentation-capacitor#2]
Thanks for providing the module. Currently, installation is not possible in capacitor 5 version. Is there any way?

**Comment by TheeMachine** [comment]
I started the version update process. See you again when the update is ready.

**Comment by DanijelPavlovic** [comment]
HI @TheeMachine, are there any updates on this topic? 

Thank you

**Comment by TheeMachine** [comment]
@DanijelPavlovic Hi, Project updated to capacitor v5 at npm. Now you can use
